"""empty message

Revision ID: 1d890129779a
Revises: 8632e11b69be
Create Date: 2020-04-11 19:51:20.544616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d890129779a'
down_revision = '8632e11b69be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'likes')
    # ### end Alembic commands ###
