"""empty message

Revision ID: 214eb54f18d9
Revises: d7a8af7b9227
Create Date: 2020-04-12 10:43:46.605650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214eb54f18d9'
down_revision = 'd7a8af7b9227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ideastags_tags_value_fkey', 'ideastags', type_='foreignkey')
    op.drop_constraint('ideastags_ideas_id_fkey', 'ideastags', type_='foreignkey')
    op.create_foreign_key(None, 'ideastags', 'tags', ['tags_value'], ['value'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ideastags', 'ideas', ['ideas_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ideastags', type_='foreignkey')
    op.drop_constraint(None, 'ideastags', type_='foreignkey')
    op.create_foreign_key('ideastags_ideas_id_fkey', 'ideastags', 'ideas', ['ideas_id'], ['id'])
    op.create_foreign_key('ideastags_tags_value_fkey', 'ideastags', 'tags', ['tags_value'], ['value'])
    # ### end Alembic commands ###
