"""empty message

Revision ID: 8190ad8014a1
Revises: 1d890129779a
Create Date: 2020-04-11 20:14:37.267093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8190ad8014a1'
down_revision = '1d890129779a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
