"""empty message

Revision ID: 8632e11b69be
Revises: 
Create Date: 2020-04-11 10:01:00.498435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8632e11b69be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('ideastags',
    sa.Column('tags_value', sa.String(), nullable=True),
    sa.Column('ideas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ideas_id'], ['ideas.id'], ),
    sa.ForeignKeyConstraint(['tags_value'], ['tags.value'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ideastags')
    op.drop_table('tags')
    op.drop_table('ideas')
    # ### end Alembic commands ###
