"""empty message

Revision ID: d7a8af7b9227
Revises: 8190ad8014a1
Create Date: 2020-04-11 20:24:04.235597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a8af7b9227'
down_revision = '8190ad8014a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'created')
    # ### end Alembic commands ###
